[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
actor-runtime = { path = "crates/actor-runtime" }
tokio = { version = "1.53", features = ["rt-multi-thread", "sync", "time", "macros", "net", "io-util"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
uuid = { version = "1.26", features = ["v7", "serde"] }
arc-swap = "1.9"
wherror = "2.4"
error-stack = "0.8"
derive_more = { version = "2.1", features = ["debug"] }
tracing = "0.1"
# dev
rstest = "0.26"
futures = "0.3"
tracing-subscriber = "0.3"

[package]
name = "actor-canvas"
version.workspace = true
edition.workspace = true

[dependencies]
actor-runtime.workspace = true
error-stack.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[profile.release]
lto = true
codegen-units = 1
