[package]
name = "canvas"
version.workspace = true
edition.workspace = true

[dependencies]
actor-runtime.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
wherror.workspace = true

[dev-dependencies]
rstest.workspace = true
futures.workspace = true
canvas-server.workspace = true
actor-runtime.workspace = true
error-stack.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
