[package]
name = "state-report"
version.workspace = true
edition.workspace = true

[dependencies]
trouper.workspace = true
zenoh.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
wherror.workspace = true

[dev-dependencies]
rstest.workspace = true
futures.workspace = true
serde.workspace = true
error-stack.workspace = true
tracing-subscriber.workspace = true
